import React from "react";
import {
  Platform,
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";
import { useRouter } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { Feather } from "@expo/vector-icons";
import { useColors } from "@/hooks/useColors";

const HERB = "#4CAF76";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  const colors = useColors();
  return (
    <View style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}>
      <Text style={[styles.sectionTitle, { color: HERB }]}>{title}</Text>
      {children}
    </View>
  );
}

function Body({ children }: { children: React.ReactNode }) {
  const colors = useColors();
  return <Text style={[styles.body, { color: colors.textSecondary }]}>{children}</Text>;
}

function Bullet({ text }: { text: string }) {
  const colors = useColors();
  return (
    <View style={styles.bulletRow}>
      <Text style={[styles.bulletDot, { color: HERB }]}>•</Text>
      <Text style={[styles.bulletText, { color: colors.textSecondary }]}>{text}</Text>
    </View>
  );
}

export default function TermsOfServiceScreen() {
  const colors = useColors();
  const insets = useSafeAreaInsets();
  const router = useRouter();
  const topPadding = Platform.OS === "web" ? 67 : insets.top;

  return (
    <View style={[styles.container, { backgroundColor: colors.background }]}>
      <View style={[styles.header, { paddingTop: topPadding + 6, borderBottomColor: colors.border }]}>
        <TouchableOpacity
          style={[styles.backBtn, { backgroundColor: colors.card, borderColor: colors.border }]}
          onPress={() => router.back()}
          activeOpacity={0.75}
        >
          <Feather name="arrow-left" size={20} color={colors.foreground} />
        </TouchableOpacity>
        <Text style={[styles.headerTitle, { color: colors.foreground, fontFamily: "Inter_700Bold" }]}>
          Terms of Service
        </Text>
        <View style={{ width: 40 }} />
      </View>

      <ScrollView
        showsVerticalScrollIndicator={false}
        contentContainerStyle={[styles.scroll, { paddingBottom: insets.bottom + 40 }]}
      >
        <Text style={[styles.lastUpdated, { color: colors.textMuted, fontFamily: "Inter_400Regular" }]}>
          Last Updated: June 2026
        </Text>

        <Section title="1. Acceptance of Terms">
          <Body>
            By downloading, installing, or using PantrySwipe, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the application.{"\n\n"}We reserve the right to update these terms at any time. Continued use of PantrySwipe following any changes constitutes acceptance of the new terms.
          </Body>
        </Section>

        <Section title="2. User Accounts">
          <Body>
            To access certain features of PantrySwipe, you may need to create an account. You are responsible for:{"\n"}
          </Body>
          <Bullet text="Maintaining the confidentiality of your password" />
          <Bullet text="All activities that occur under your account" />
          <Bullet text="Notifying us immediately of any unauthorised access" />
          <Body>
            {"\n"}You must provide accurate and complete information when creating your account. PantrySwipe accounts are for personal use only and may not be shared.
          </Body>
        </Section>

        <Section title="3. Pantry Data">
          <Body>
            You are solely responsible for maintaining accurate and up-to-date pantry information within the app. PantrySwipe does not independently verify the accuracy of ingredient data, expiry dates, or quantities you enter.{"\n\n"}Always use your own judgement when assessing the freshness and safety of food in your pantry.
          </Body>
        </Section>

        <Section title="4. Barcode Scanning">
          <Body>
            Product information retrieved via barcode scanning is sourced from third-party databases including Open Food Facts and UPCitemDB. PantrySwipe does not guarantee the accuracy, completeness, or currency of this information.{"\n\n"}Nutritional data, allergen information, and product descriptions are provided for reference only. Always verify this information against the physical product label.
          </Body>
        </Section>

        <Section title="5. AI Recipe Suggestions">
          <Body>
            Recipes generated by PantrySwipe are produced by AI and are provided for informational and inspirational purposes only. Before preparing any recipe, you must:
          </Body>
          <Bullet text="Check all ingredients for freshness and safety" />
          <Bullet text="Verify allergen information independently" />
          <Bullet text="Follow proper food safety and hygiene practices" />
          <Bullet text="Confirm that food has not passed its expiry date" />
          <Bullet text="Cook food to the correct internal temperatures" />
          <Body>
            {"\n"}AI-generated recipes may occasionally contain errors. PantrySwipe is not responsible for the outcome of recipes prepared using the app.
          </Body>
        </Section>

        <Section title="6. Food Safety Disclaimer">
          <Body>
            PantrySwipe does not guarantee the safety, freshness, or fitness for consumption of any food items tracked within the app. Expiry reminders are provided as a convenience feature only and should not be solely relied upon to determine food safety.{"\n\n"}You are solely responsible for ensuring that any food you consume is safe. Always use your senses and common sense to evaluate food before eating it.
          </Body>
        </Section>

        <Section title="7. Intellectual Property">
          <Body>
            The PantrySwipe name, logo, branding, icons, app design, and underlying software are the exclusive intellectual property of PantrySwipe and its licensors. All rights are reserved.{"\n\n"}You may not copy, reproduce, distribute, or create derivative works from any part of PantrySwipe without express written permission.
          </Body>
        </Section>

        <Section title="8. Prohibited Use">
          <Body>You agree not to:</Body>
          <Bullet text="Use PantrySwipe for any unlawful or prohibited purpose" />
          <Bullet text="Attempt to reverse engineer or decompile the app" />
          <Bullet text="Upload or transmit any malicious code or content" />
          <Bullet text="Interfere with or disrupt PantrySwipe servers or networks" />
          <Bullet text="Attempt to gain unauthorised access to other users' accounts" />
          <Bullet text="Use automated means to scrape or extract app data" />
          <Bullet text="Impersonate any person or entity" />
        </Section>

        <Section title="9. Limitation of Liability">
          <Body>
            To the fullest extent permitted by law, PantrySwipe shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the app, including but not limited to:
          </Body>
          <Bullet text="Incorrect or incomplete barcode or product data" />
          <Bullet text="Errors or omissions in AI-generated recipes" />
          <Bullet text="Food spoilage, foodborne illness, or allergic reactions" />
          <Bullet text="Loss of pantry data or account information" />
          <Bullet text="Service interruptions or downtime" />
          <Body>
            {"\n"}Our total liability to you for any claim arising from use of PantrySwipe shall not exceed the amount you paid for the app in the 12 months preceding the claim.
          </Body>
        </Section>

        <Section title="10. Account Termination">
          <Body>
            PantrySwipe reserves the right to suspend or permanently terminate accounts that violate these Terms of Service, engage in abusive behaviour, or pose a risk to other users or the platform.{"\n\n"}You may delete your account at any time from the app settings. Upon deletion, your personal data will be removed in accordance with our Privacy Policy.
          </Body>
        </Section>

        <Section title="11. Changes to These Terms">
          <Body>
            We may revise these Terms of Service from time to time. When material changes are made, we will notify you within the app and update the "Last Updated" date above.{"\n\n"}Your continued use of PantrySwipe after such notification constitutes acceptance of the updated terms.
          </Body>
        </Section>

        <Section title="12. Governing Law">
          <Body>
            These Terms of Service are governed by and construed in accordance with the laws of Singapore. Any disputes arising under or in connection with these terms shall be subject to the exclusive jurisdiction of the courts of Singapore.
          </Body>
        </Section>

        <Section title="13. Contact Us">
          <Body>
            If you have any questions about these Terms of Service, please contact us at:
          </Body>
          <Text style={[styles.contactEmail, { color: HERB, fontFamily: "SpaceGrotesk_600SemiBold" }]}>
            support@pantryswipe.app
          </Text>
        </Section>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingBottom: 14,
    borderBottomWidth: 1,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  headerTitle: { fontSize: 20, letterSpacing: -0.3 },
  scroll: { paddingTop: 8, paddingHorizontal: 16, gap: 12 },
  lastUpdated: { fontSize: 12, textAlign: "center", paddingVertical: 10 },
  card: {
    borderRadius: 16,
    borderWidth: 1,
    padding: 18,
    gap: 10,
  },
  sectionTitle: {
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
    letterSpacing: 0.3,
    marginBottom: 2,
  },
  body: {
    fontSize: 14,
    lineHeight: 22,
    fontFamily: "Inter_400Regular",
  },
  bulletRow: {
    flexDirection: "row",
    gap: 8,
    paddingLeft: 4,
  },
  bulletDot: {
    fontSize: 14,
    lineHeight: 22,
    fontFamily: "Inter_400Regular",
  },
  bulletText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 22,
    fontFamily: "Inter_400Regular",
  },
  contactEmail: {
    fontSize: 15,
    marginTop: 4,
  },
});
